@echo off
echo Starting Backend...
start "Backend API" cmd /k "cd backend && venv\Scripts\activate && uvicorn main:app --reload --port 8001"
echo Starting Frontend...
start "Frontend App" cmd /k "npm run dev"
echo Servers started!
